/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

version = "0.0.1"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

javafx {
    version = "17"
    modules = listOf("javafx.base")
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir(listOf("src"))
        }
    }
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.0")
    implementation("org.javatuples:javatuples:1.2")
}

application {
    mainClass.set("Main")
}

val logDir = File(rootDir, "logs")

val createLogDir by tasks.registering {
    doLast {
        if (!logDir.exists()) {
            logDir.mkdirs()
            println("Created log directory at: ${logDir.absolutePath}")
        }
    }
}

tasks.named("run") {
    dependsOn(createLogDir)
}


tasks.named<JavaExec>("run") {
    dependsOn(createLogDir)
    standardInput = System.`in`  // Pipe System.in to the app
}